area = float(input())
price = (area * float(7.61))
discount = float(price * float(0.18))
finalprice = float(price - discount)
print(f'The final price is : {finalprice} lv.')
print(f'The discount is: {discount} lv.')
